name: LLaMa.cpp wheel generator

on: workflow_dispatch

jobs:
  gen_wheels:
    name: Generate wheels
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Build the wheels
      run: |
        tools/run_image.sh pytorch/manylinux-builder:rocm5.2 tools/build_llama_cpp.sh

    - name: Store wheels
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: llama-cpp-python/dist

