name: Base OS + ROCm + PyTorch Docker image.

on:
  push:
    paths:
      - '.github/workflows/docker-rx5500_pt.yml'
      - 'docker_base/Dockerfile'
      - 'docker_base/*.sh'
    tags:
      - v*
  repository_dispatch:
    types: [build_rx5500_pt]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        cd docker_base
        ./build.sh
        ./push.sh
