name: Ubuntu analyzer

on: workflow_dispatch

jobs:
  gen_wheels:
    name: Look what is installed
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Build the wheels
      run: |
        tools/run_image.sh pytorch/manylinux-builder:rocm5.2 tools/build_gptq.sh

    - name: Store wheels
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: GPTQ-for-LLaMa-ROCm/dist

    - name: Store build
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: GPTQ-for-LLaMa-ROCm/build

