name: Ubuntu analyzer

on: workflow_dispatch

jobs:
  gen_wheels:
    name: Generate wheels
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - name: Check what is installed
      run: |
        df -h
        echo "***********************************************"
        cd /
        sudo du -hsc *
        echo "***********************************************"
        cd /usr
        sudo du -hsc *
        echo "***********************************************"
        cd /usr/share
        sudo du -hsc *
        echo "***********************************************"
        cd /opt
        sudo du -hsc *

