name: Ubuntu analyzer

on: workflow_dispatch

jobs:
  gen_wheels:
    name: Look what is installed
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - name: Check what is installed
      run: |
        df -h
        echo "***********************************************"
        cd /
        # sudo du -hsc *
        echo "***********************************************"
        cd /usr
        #sudo du -hsc *
        echo "***********************************************"
        cd /usr/share
        sudo du -hsc * | sort -rh
        echo "***********************************************"
        cd /opt
        sudo du -hsc * | sort -rh
        echo "*********/usr/local"
        cd /usr/local
        sudo du -hsc * | sort -rh
        echo "*********/opt/hostedtoolcache"
        cd /opt/hostedtoolcache
        sudo du -hsc * | sort -rh
        echo "*********/opt/microsoft"
        cd /opt/microsoft
        sudo du -hsc * | sort -rh
        echo "***********************************************"
        sudo rm -R /opt/hostedtoolcache /opt/microsoft /opt/az /opt/google
        df -h

